name: Update CHANGELOG.md
on:
  push:
    tags:
      - 'v*.*.*'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update_changelog:
    name: Update the changelog based on the latest commits
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(changelog): update changelog [skip ci]"
          file_pattern: CHANGELOG.md
          branch: main